version: "2"

services:
  zookeeper1:
    hostname: zookeeper1
    networks:
      - zoo
    build:
      context: ./docker/zookeeper
      dockerfile: Dockerfile.zookeeper
      args:
        myid: 1
  zookeeper2:
    hostname: zookeeper2
    networks:
      - zoo
    build:
      context: ./docker/zookeeper
      dockerfile: Dockerfile.zookeeper
      args:
        myid: 2
  zookeeper3:
    hostname: zookeeper3
    networks:
      - zoo
    build:
      context: ./docker/zookeeper
      dockerfile: Dockerfile.zookeeper
      args:
        myid: 3
  zookeeper4:
    hostname: zookeeper4
    networks:
      - zoo
    build:
      context: ./docker/zookeeper
      dockerfile: Dockerfile.zookeeper
      args:
        myid: 4
  zookeeper5:
    hostname: zookeeper5
    networks:
      - zoo
    build:
      context: ./docker/zookeeper
      dockerfile: Dockerfile.zookeeper
      args:
        myid: 5
  zkui:
    image: qnib/zkui:latest
    hostname: zkui
    links:
      - zookeeper1:zookeeper1
      - zookeeper2:zookeeper2
      - zookeeper3:zookeeper3
      - zookeeper4:zookeeper4
      - zookeeper5:zookeeper5
    environment:
      - ZKUI_ZK_SERVER=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181,zookeeper4:2181,zookeeper5:2181
    ports:
      - "9090:9090"
    networks:
      - zoo

networks:
  zoo:
    driver: bridge